apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.host }}
  namespace: {{ .Values.namespace }}
spec:
  commonName: {{ .Values.host }}
  secretName: {{ .Values.ingress.tls.secretName }}
  dnsNames:
    - {{ .Values.host }}
  issuerRef:
    name: {{ .Values.ingress.tls.clusterIssuer }}
    kind: ClusterIssuer