apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubelogin.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubelogin.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubelogin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubelogin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: REDIRECT_URI
              value: http://kubelogin.test.viarezo.fr
            - name: API_URL
              value: https://138.195.139.40:6443
            - name: ROOT_CRT
              valueFrom:
                secretKeyRef:
                  name: kubelogin-secret
                  key: root-crt
            - name: ROOT_KEY
              valueFrom:
                secretKeyRef:
                  name: kubelogin-secret
                  key: root-key
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: kubelogin-secret
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kubelogin-secret
                  key: client-secret
          

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}