apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelogin
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  namespace: kubelogin
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io