apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viarezo-team
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viarezo-team
subjects:
- kind: Group
  name: viarezo-team
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: viarezo-team
  apiGroup: rbac.authorization.k8s.io